projects: [{ id: "dittopay-signup-flow-ns" }]
variants: [{ id: "base" }, { id: "portuguesebr" }, { id: "french" }, { id: "spanish" }]
outDir: "./src/ditto"
outputs:
  - format: json
    framework: i18next
    type: module
